server:
  port: 9002

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 50MB # 限制文件上传的大小
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/music?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

# mybatis
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# fastDFS
fdfs:
  so-timeout: 5000 # 超时时间
  connect-timeout: 2000 # 连接超时时间
  thumb-image: # 缩略图
    width: 150
    height: 150
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    123.207.87.254:22122

# customize properties start
upload:
    local-path: G:\vinspier-project\upload\
    server-path: http://source.vinspier.com/
# customize properties end